rerun:
	python3 RunPF.py ../../data/pf/simple_world_path1.pickle 250
	python3 RunPF.py ../../data/pf/simple_world_path2.pickle 250
	python3 RunPF.py ../../data/pf/rooms_world_path2.pickle 500

all:
	python3 RunPF.py ../../data/pf/simple_world_path1.pickle 30
	python3 RunPF.py ../../data/pf/simple_world_path2.pickle 100
	python3 RunPF.py ../../data/pf/simple_world_path3.pickle 500
	python3 RunPF.py ../../data/pf/rooms_world_path1.pickle 40
	python3 RunPF.py ../../data/pf/rooms_world_path2.pickle 100
	python3 RunPF.py ../../data/pf/loops_world_path0.pickle 100
	python3 RunPF.py ../../data/pf/loops_world_path1.pickle 10
	python3 RunPF.py ../../data/pf/loops_world_path2.pickle 250

simple1:
	python3 RunPF.py ../../data/pf/simple_world_path1.pickle 30

simple2:
	python3 RunPF.py ../../data/pf/simple_world_path2.pickle 100

simple3:
	python3 RunPF.py ../../data/pf/simple_world_path3.pickle 500

room1:
	python3 RunPF.py ../../data/pf/rooms_world_path1.pickle 40

room2:
	python3 RunPF.py ../../data/pf/rooms_world_path2.pickle 100

loops0:
	python3 RunPF.py ../../data/pf/loops_world_path0.pickle 100

loops1:
	python3 RunPF.py ../../data/pf/loops_world_path1.pickle 10

loops2:
	python3 RunPF.py ../../data/pf/loops_world_path2.pickle 250
