pb:
	python3 RunMDP.py --gamma 0.1  --noise 0.2 --epsilon 0.001
	python3 RunMDP.py --gamma 0.99 --noise 0.2 --epsilon 0.001

pc:
	python3 RunMDP.py --gamma 0.1  --noise 0.2 --epsilon 0.001
	python3 RunMDP.py --gamma 0.99 --noise 0.2 --epsilon 0.001
	python3 RunMDP.py --gamma 0.99 --noise 0.5 --epsilon 0.001

p2:
	python3 RunMDP.py --gamma 0.99 --noise 0.2 --epsilon 0.001

.PHONY: clean
clean:
	rm *.png
